version: '3'

services:
  wrong-notebook:
    build: .
    image: wrong-notebook:local
    container_name: wrong-notebook
    restart: always
    ports:
      - "3000:3000"
    environment:
      # NEXTAUTH_URL 根据实际情况设置你的信息
      #- NEXTAUTH_URL=http://your_domain_name:3000
      - NEXTAUTH_SECRET=bhEAJ2OIkXGHSkJxs8twXEvm+lO6F27HTsAet9hTh3M=
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
      - ./config:/app/config

